language: cpp
compiler: gcc
os: linux



addons:
  apt:
    packages:
      - libcppunit-dev
      - scons

script: scons test


before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search